POST http://localhost:3000/transactions/addone HTTP/1.1
content-type: application/json
{
    "userid": '675e8fcee31c283726c58326',
    "type": "credit",
    "amount":12000,
    "description": "salary"
}